apiVersion: qualitorque.io/v1
kind: Blueprint
metadata:
  name: eks-demo-blueprint
  description: "EKS cluster deployment blueprint"
spec:
  grains:
    - name: eks-cluster
      type: terraform
      path: ./
      inputs:
        region: us-east-1
        cluster_name: yana-eks-demo
        vpc_id: vpc-066d45cb6f15cce6e
        subnet_ids:
          - subnet-04b1589da0f453bf0
          - subnet-024c12ca933afee95
  
  environments:
    devbox:
      inputs:
        region: us-east-1
        cluster_name: yana-eks-devbox
        vpc_id: vpc-066d45cb6f15cce6e
        subnet_ids:
          - subnet-04b1589da0f453bf0
          - subnet-024c12ca933afee95
      tags:
        - environment: development
        - team: engineering
        - temporary: true
    
    staging:
      inputs:
        region: us-east-1
        cluster_name: yana-eks-staging
        vpc_id: vpc-066d45cb6f15cce6e
        subnet_ids:
          - subnet-04b1589da0f453bf0
          - subnet-024c12ca933afee95
      tags:
        - environment: staging
        - team: development
    
    production:
      inputs:
        region: us-east-1
        cluster_name: yana-eks-prod
        vpc_id: vpc-066d45cb6f15cce6e
        subnet_ids:
          - subnet-04b1589da0f453bf0
          - subnet-024c12ca933afee95
      tags:
        - environment: production
        - team: platform
