environment:
  environment_name: eks-production
  description: "Production EKS environment"
  owner_email: yana@quali.com
  state: active
  labels:
    environment: production
    team: platform
    cost-center: ops
  inputs:
    region: us-east-1
    cluster_name: yana-eks-prod
    vpc_id: vpc-066d45cb6f15cce6e
    subnet_ids: "subnet-04b1589da0f453bf0,subnet-024c12ca933afee95"
  outputs:
    cluster_endpoint:
      value: '{{ .grains.eks-cluster.outputs.cluster_endpoint }}'
      quick: true
    cluster_name:
      value: '{{ .grains.eks-cluster.outputs.cluster_name }}'
      quick: true