environment:
  environment_name: eks-staging
  description: "Staging EKS environment for testing"
  owner_email: yana@quali.com
  state: active
  labels:
    environment: staging
    team: development
    cost-center: dev
  inputs:
    region: us-east-1
    cluster_name: yana-eks-staging
    vpc_id: vpc-066d45cb6f15cce6e
    subnet_ids: "subnet-04b1589da0f453bf0,subnet-024c12ca933afee95"
  outputs:
    cluster_endpoint:
      value: '{{ .grains.eks_cluster.outputs.cluster_endpoint }}'
      quick: true
    cluster_name:
      value: '{{ .grains.eks_cluster.outputs.cluster_name }}'
      quick: true