apiVersion: qualitorque.io/v1
kind: Environment
metadata:
  name: staging
  description: "Staging EKS environment for testing"
spec:
  blueprint: eks-demo-blueprint
  inputs:
    region: us-east-1
    cluster_name: yana-eks-staging
    vpc_id: vpc-066d45cb6f15cce6e
    subnet_ids:
      - subnet-04b1589da0f453bf0
      - subnet-024c12ca933afee95
  tags:
    - environment: staging
    - team: development
    - cost-center: dev